version: "3"
services:
  sonarserver:
    image: sonarqube:lts-community
    volumes:
        - sonarqube_data:/opt/sonarqube/data
        - sonarqube_logs:/opt/sonarqube/logs
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: true 
    ports:
      - "9000:9000"
    restart: always
    networks:
      - default
volumes:
    sonarqube_data: #empty =  platform’s default configuration for creating a volume
    sonarqube_logs: #empty =  platform’s default configuration for creating a volume
networks:
    default:
